### PR TITLE
Add clearer error when more than one oneOf rule matched

### LINKED ISSUE #164: handling of 'oneOf' rules less than optimal
* JSON::Validator version: 3.11
* Perl version: not relevant

When more than one 'oneOf' rule matches, the error is not correct. The following script demonstrates the issue:

```
use strict;
use warnings;
use JSON::Validator;

my $schema = {
    type => 'object',
    properties => {},
    additionalProperties => {
        oneOf => [
            { type => 'integer', minimum => 1 },
            { type => 'integer', minimum => 2 },
            { type => 'integer', maximum => 3 },
        ],
    },
};

my $jv = JSON::Validator->new;
$jv->load_and_validate_schema($schema, { schema => 'http://json-schema.org/draft-07/schema#' });

my $data = { foo => 1 };
my @errors = $jv->validate($data, $schema);
use Data::Dumper;
print STDERR "### got errors: ", Dumper(\@errors);

# got message: '/oneOf/1 1 < minimum(2)'
# but it should be: 'oneOf Multiple rules matched: /oneOf/0, /oneof/2.'
```

In the `_validate_one_of` sub, I think we should be tracking all the rules that *do* match, and then if `@matched` != 1, the path to all the matching rules can be easily provided in the error message.  As it is now, only the *failing* rules are tracked, and this is used to construct the error message, but that is not helpful here.

### PR DESCRIPTION
**Pull request by karenetheridge**
fixes #164.

### CODE REVIEW

**Comment by karenetheridge** [comment]
> Would it be possible to let the user know which rules that failed?

Yes, that should be possible with a bit of juggling. I'll push an update.

**Comment by jhthorsen** [comment]
Don’t do it if it’s a lot of hassle/lines of code.

**Comment by karenetheridge** [comment]
It would be a few lines of code -- we can get all the failure rules numbers by doing

    -    push @expected, $schema_type;
    +    push @expected, [$i, $schema_type];

and then `@failed = sort {$a <=> $b} map $_->[0], @errors, @expected`, but then we need to subtract that list from `0..@rules-1` to get the rules that *passed*. I don't see how to do it without at least one extra local variable :)

**Comment by karenetheridge** [comment]
I pushed another commit that uses the indexes of the matching oneOf rules, which you can squash if you like it, or ignore if you don't :)

**Comment by karenetheridge** [comment]
I force-pushed a much nicer change for adding passing indexes. :)

**Comment by karenetheridge** [comment]
and done!

**Pull request merged**
